# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qoute', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='book',
            name='qoutes',
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(to='shop.Comment'),
        ),
        migrations.AddField(
            model_name='book',
            name='qoutes',
            field=models.ManyToManyField(to='shop.Qoute'),
        ),
    ]
