# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buying',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(default='e2EpirMb7eOb5fYXIl1mSf0tdJPU6hmktQKRF3jc', max_length=40),
        ),
    ]
