# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160528_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(default='M14QSsxfhsItCrA7XJQ6UhrI7sX529UTUc6yxhD3', max_length=40),
        ),
    ]
