# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20160528_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(default='qKfN1OKBT32Y70vABi7mwKBb2SXrAYDHdqeAjJ3I', max_length=40),
        ),
    ]
