# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20160528_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(blank=True, to='shop.Comment'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='shop.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(blank=True, to='shop.Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='qoutes',
            field=models.ManyToManyField(blank=True, to='shop.Qoute'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_bought',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(default='IxXbh6g3KJngUPxBw4uKCWMXgeFdOY3Wi3JEHXHQ', max_length=40),
        ),
    ]
