# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20160528_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_root',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(default='EQtHWsibqY1yEjajkMEgELyXhr3PLTNMGYSMQc5E', max_length=40),
        ),
    ]
