# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20160528_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(default='ysU6YqYPudPMa4rP3C9rxI2QcA7YaN9m1Q1dcpOd', max_length=40),
        ),
    ]
