# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20160528_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='special_id',
            field=models.CharField(default='7Fb2Od40MXsErVcMjD0m', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(default='UT7SWSLfXLwOogAtM5LT5voqNWUO4Se5HDdVucTj', max_length=40),
        ),
    ]
