# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20160604_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='special_id',
            field=models.CharField(default='Ucw5FAgKBkVDKbyK2YJS', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(default='n8VDoBewljqkqvvqICjJHe7xJbbCSbeBc9yVpp10', max_length=40, unique=True),
        ),
    ]
